version: '3'
networks:
  ocpp_network:
    external: true
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    command: python manage.py runserver 0.0.0.0:8997
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8997:8997"
    networks:
      ocpp_network:
        ipv4_address: 172.21.0.31
    env_file:
      - .env
  proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    command: python proxy.py
    volumes:
      - .:/app
    ports:
      - "8998:8998"
    networks:
      ocpp_network:
        ipv4_address: 172.21.0.32
    env_file:
      - .env