# Generated by Django 3.2.25 on 2024-05-30 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('csms_name', models.CharField(max_length=100, verbose_name='CSMS Name')),
                ('connect_url', models.CharField(max_length=100, verbose_name='Connection URL')),
                ('cp_id', models.CharField(max_length=100, verbose_name='Charge Point ID')),
                ('auth_key', models.CharField(max_length=100, verbose_name='Auth Key')),
                ('sec_prof', models.CharField(max_length=100, verbose_name='Security Profile')),
                ('connection_status', models.CharField(default='Disconnected', max_length=100, verbose_name='Connection')),
            ],
        ),
        migrations.CreateModel(
            name='ChargePoint',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Charge Point Name')),
                ('status', models.CharField(default='N/A', max_length=100, verbose_name='Status')),
                ('connection_status', models.CharField(default='Disconnected', max_length=100, verbose_name='Connection')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True)),
                ('token_type', models.CharField(max_length=50)),
                ('expires_in', models.IntegerField()),
                ('scope', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('INFO', 'Information'), ('ERROR', 'Error')], max_length=10)),
                ('message', models.TextField()),
                ('raw_message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('authorization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ocpp_hub_app.authorization')),
                ('chargepoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ocpp_hub_app.chargepoint')),
            ],
        ),
        migrations.AddField(
            model_name='authorization',
            name='chargepoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocpp_hub_app.chargepoint'),
        ),
    ]
