# Generated by Django 3.2.25 on 2024-08-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocpp_hub_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='error_code',
        ),
        migrations.AlterField(
            model_name='logentry',
            name='action',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='from_entity',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='to_entity',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
