# Generated by Django 3.2.25 on 2024-07-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocpp_hub_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logentry',
            old_name='source',
            new_name='from_entity',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='destinations',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='raw_data',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='related_entry',
        ),
        migrations.AddField(
            model_name='logentry',
            name='raw_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='to_entity',
            field=models.JSONField(default=dict),
        ),
    ]
