# Generated by Django 3.2.25 on 2024-06-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocpp_hub_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='event_type',
            field=models.CharField(max_length=50),
        ),
    ]
