# Generated by Django 3.2.25 on 2024-05-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocpp_hub_app', '0002_alter_chargepoint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorization',
            name='status',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
