# Generated by Django 3.2.25 on 2024-05-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocpp_hub_app', '0003_alter_authorization_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargepoint',
            name='status',
            field=models.CharField(default='Disconnected', max_length=100),
        ),
    ]
