# Generated by Django 3.2.25 on 2024-05-26 15:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ocpp_hub_app', '0004_alter_chargepoint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorization',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='status',
            field=models.CharField(default='Disconnected', max_length=100),
        ),
        migrations.AlterField(
            model_name='chargepoint',
            name='status',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('INFO', 'Information'), ('ERROR', 'Error')], max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('authorization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ocpp_hub_app.authorization')),
                ('chargepoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ocpp_hub_app.chargepoint')),
            ],
        ),
    ]
