# Generated by Django 3.2.25 on 2024-05-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocpp_hub_app', '0005_auto_20240526_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='raw_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
