# Generated by Django 3.2.25 on 2024-05-26 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocpp_hub_app', '0006_logentry_raw_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorization',
            name='auth_key',
            field=models.CharField(max_length=255, verbose_name='Auth Key'),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='chargepoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocpp_hub_app.chargepoint', verbose_name='Charge Point'),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='connect_url',
            field=models.CharField(max_length=255, verbose_name='Connect URL'),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='cp_id',
            field=models.CharField(max_length=100, verbose_name='Charge Point ID'),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='csms_name',
            field=models.CharField(max_length=100, verbose_name='CSMS Name'),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='sec_prof',
            field=models.IntegerField(verbose_name='Security Profile'),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='status',
            field=models.CharField(default='Disconnected', max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='chargepoint',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='chargepoint',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Charge Point Name'),
        ),
        migrations.AlterField(
            model_name='chargepoint',
            name='status',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Status'),
        ),
    ]
