# Generated by Django 3.2.25 on 2024-05-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocpp_hub_app', '0007_auto_20240526_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargepoint',
            name='connection_status',
            field=models.CharField(default='Disconnected', max_length=100, verbose_name='Connection'),
        ),
    ]
