# Generated by Django 3.2.25 on 2024-05-27 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocpp_hub_app', '0008_chargepoint_connection_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorization',
            name='status',
        ),
        migrations.RemoveField(
            model_name='authorization',
            name='uuid',
        ),
        migrations.AddField(
            model_name='authorization',
            name='connection_status',
            field=models.CharField(default='Disconnected', max_length=100, verbose_name='Connection'),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='auth_key',
            field=models.CharField(max_length=100, verbose_name='Auth Key'),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='chargepoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocpp_hub_app.chargepoint'),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='connect_url',
            field=models.URLField(verbose_name='Connection URL'),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='sec_prof',
            field=models.CharField(max_length=100, verbose_name='Security Profile'),
        ),
    ]
