# Generated by Django 3.2.25 on 2024-05-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocpp_hub_app', '0009_auto_20240527_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorization',
            name='connect_url',
            field=models.CharField(max_length=100, verbose_name='Connection URL'),
        ),
    ]
